#!/usr/bin/perl

use strict;
use warnings;

my $VERSION = "1.0";
my $HOME = $ENV{HOME};
my $TRACKERSFILE = "$HOME/.trackers";

print "mytorrent v$VERSION\n";
print "==================\n";

print "Loading in $HOME/.trackers:\n";
if (! -f $TRACKERSFILE)
{
	print "trackers list not found, running updater:\n";
	system("updatetrackers");
}
my $SawVersion = "";
open my $file, '<', $TRACKERSFILE or die("Unable to open tracker file: $!");
while(<$file>)
{
	my $CurLine = $_;
	chop($CurLine);
	if ($CurLine eq "")
	{
		next;
	}
	if ($SawVersion eq "")
	{
		print "File version: $CurLine\n";
		$SawVersion = "true";
	}
	else
	{
		print "Saw tracker: $CurLine\n";
	}
}
close $file;


my $TorrentCommand = "/usr/bin/transmission-create -c \"File supplied by Yu-Gi-Oh City - yugioph.gameplayer.club\" -t \"udp://torrentclub.space:6969/announce\" -t \"http://torrentclub.space:6969/announce\" -t \"udp://tracker.open-internet.nl:6969/announce\" -t \"udp://tracker.opentrackr.org:1337/announce\" -t \"udp://tracker.ilibr.org:80/announce\" -t \"http://p4p.arenabg.com:1337/announce\" -t \"udp://tracker.openbittorrent.com:6969/announce\" -t \"http://mgtracker.org:6969/announce\" -t \"http://openbittorrent.com:80/announce\" -t \"udp://tracker.torrent.eu.org:451/announce\" -t \"udp://opentracker.i2p.rocks:6969/announce\" -t \"udp://exodus.desync.com:6969/announce\" -t \"udp://public.popcorn-tracker.org:6969/announce\"";
my $CurFile = "";
if ($#ARGV == 0)
{
	$CurFile = $ARGV[0];
}
else 
{
	print "Must specify the file to process\n";
	exit 1;
}

print "Creating torrent file for $CurFile\n";

system("$TorrentCommand \"$CurFile\"");

exit 0;
